//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diabetes_Final.DataBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class CITAS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CITAS()
        {
            this.NOTAS = new HashSet<NOTAS>();
        }
    
        public int ID_CITAS { get; set; }
        public string ASISTENCIA { get; set; }
        public System.DateTime FECHA_CITA { get; set; }
        public System.TimeSpan HORA_CITA { get; set; }
        public int ID_DATOSCITA { get; set; }
        public int ID_TIPO_CITAS { get; set; }
        public int ID_PERSONA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NOTAS> NOTAS { get; set; }
        public virtual DATOS_CITA DATOS_CITA { get; set; }
        public virtual PERSONAS PERSONAS { get; set; }
        public virtual TIPO_CITAS TIPO_CITAS { get; set; }
    }
}
