//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diabetes_Final.DataBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONFERENCIAS
    {
        public int ID_CONFERENCIAS { get; set; }
        public string ASISTENCIA { get; set; }
        public System.DateTime FECHA_CONFERENCIAS { get; set; }
        public System.TimeSpan HORA_CONFERENCIAS { get; set; }
        public int ID_PERSONA { get; set; }
        public int ID_NOMCONFERENCIA { get; set; }
    
        public virtual NOM_CONFERENCIA NOM_CONFERENCIA { get; set; }
        public virtual PERSONAS PERSONAS { get; set; }
    }
}
