//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diabetes_Final.DataBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class ELEMENTOS_PERMISOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ELEMENTOS_PERMISOS()
        {
            this.ELEMENTO_PERMITIDO = new HashSet<ELEMENTO_PERMITIDO>();
        }
    
        public int ID_ELEMENTOS_PERMISOS { get; set; }
        public int ID_ELEMENTOS { get; set; }
        public int ID_PERMISOS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ELEMENTO_PERMITIDO> ELEMENTO_PERMITIDO { get; set; }
        public virtual ELEMENTOS ELEMENTOS { get; set; }
        public virtual PERMISOS PERMISOS { get; set; }
    }
}
