//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diabetes_Final.DataBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class ELEMENTO_PERMITIDO
    {
        public int ID_ELEMENTO_PERMITIDO { get; set; }
        public int ID_TIPO_USUARIO { get; set; }
        public int ID_ELEMENTOS_PERMISOS { get; set; }
    
        public virtual ELEMENTOS_PERMISOS ELEMENTOS_PERMISOS { get; set; }
        public virtual TIPO_USUARIO TIPO_USUARIO { get; set; }
    }
}
