//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diabetes_Final.DataBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESPECIALISTA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ESPECIALISTA()
        {
            this.DATOS_CITA = new HashSet<DATOS_CITA>();
            this.NOTAS = new HashSet<NOTAS>();
        }
    
        public int ID_ESPECIALISTA { get; set; }
        public string NOMBRE_ESP { get; set; }
        public string APELLIDOP_ESP { get; set; }
        public string APELLIDOM_ESP { get; set; }
        public int ID_TIPOESP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DATOS_CITA> DATOS_CITA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NOTAS> NOTAS { get; set; }
        public virtual TIPO_ESPECIALISTA TIPO_ESPECIALISTA { get; set; }
    }
}
