//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diabetes_Final.DataBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEDICION_GLUCOSA
    {
        public int ID_MEDICION_GLUCOSA { get; set; }
        public int PRIMERA_MEDICION { get; set; }
        public System.DateTime FECHA_MEDICION_GLUCOSA { get; set; }
        public System.TimeSpan HORA_MEDICION_GLUCOSA { get; set; }
        public double RESULTADO_MEDICION_GLUCOSA { get; set; }
        public int ID_TIPMEDICION { get; set; }
        public int ID_PERSONA { get; set; }
    
        public virtual PERSONAS PERSONAS { get; set; }
        public virtual Tipo_De_Medicion Tipo_De_Medicion { get; set; }
    }
}
