//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diabetes_Final.DataBD
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbDiabetesEntities : DbContext
    {
        public dbDiabetesEntities()
            : base("name=dbDiabetesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CALENDARIO_7PASOS> CALENDARIO_7PASOS { get; set; }
        public virtual DbSet<CITAS> CITAS { get; set; }
        public virtual DbSet<CONFERENCIAS> CONFERENCIAS { get; set; }
        public virtual DbSet<CUESTIONARIO_CONOCIMIENTOS> CUESTIONARIO_CONOCIMIENTOS { get; set; }
        public virtual DbSet<DATOS_CITA> DATOS_CITA { get; set; }
        public virtual DbSet<ELEMENTO_PERMITIDO> ELEMENTO_PERMITIDO { get; set; }
        public virtual DbSet<ELEMENTOS> ELEMENTOS { get; set; }
        public virtual DbSet<ELEMENTOS_PERMISOS> ELEMENTOS_PERMISOS { get; set; }
        public virtual DbSet<ESPECIALISTA> ESPECIALISTA { get; set; }
        public virtual DbSet<ESTATUS_USU> ESTATUS_USU { get; set; }
        public virtual DbSet<MEDICION_GLUCOSA> MEDICION_GLUCOSA { get; set; }
        public virtual DbSet<MODULOS> MODULOS { get; set; }
        public virtual DbSet<NOM_CONFERENCIA> NOM_CONFERENCIA { get; set; }
        public virtual DbSet<NOTAS> NOTAS { get; set; }
        public virtual DbSet<PERFIL_MODULOS> PERFIL_MODULOS { get; set; }
        public virtual DbSet<PERMISOS> PERMISOS { get; set; }
        public virtual DbSet<PERSONAS> PERSONAS { get; set; }
        public virtual DbSet<PESO_TALLA> PESO_TALLA { get; set; }
        public virtual DbSet<PREGUNTA> PREGUNTA { get; set; }
        public virtual DbSet<PREGUNTA_C> PREGUNTA_C { get; set; }
        public virtual DbSet<PREGUNTAS_CUESTIONARIO> PREGUNTAS_CUESTIONARIO { get; set; }
        public virtual DbSet<PREGUNTAS_PRUEBA> PREGUNTAS_PRUEBA { get; set; }
        public virtual DbSet<PRUEBA_BECK> PRUEBA_BECK { get; set; }
        public virtual DbSet<Recomendaciones> Recomendaciones { get; set; }
        public virtual DbSet<RESPUESTA_C> RESPUESTA_C { get; set; }
        public virtual DbSet<RESPUESTAS> RESPUESTAS { get; set; }
        public virtual DbSet<TIPO_ACTIVIDAD> TIPO_ACTIVIDAD { get; set; }
        public virtual DbSet<TIPO_CITAS> TIPO_CITAS { get; set; }
        public virtual DbSet<Tipo_De_Medicion> Tipo_De_Medicion { get; set; }
        public virtual DbSet<TIPO_ESPECIALISTA> TIPO_ESPECIALISTA { get; set; }
        public virtual DbSet<TIPO_USUARIO> TIPO_USUARIO { get; set; }
        public virtual DbSet<USUARIO> USUARIO { get; set; }
    }
}
