//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diabetes_Final.DataBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOTAS
    {
        public int ID_NOTA { get; set; }
        public string TXT_NOTA { get; set; }
        public int ID_ESPECIALISTA { get; set; }
        public int ID_CITAS { get; set; }
    
        public virtual CITAS CITAS { get; set; }
        public virtual ESPECIALISTA ESPECIALISTA { get; set; }
    }
}
