//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diabetes_Final.DataBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSONAS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PERSONAS()
        {
            this.CALENDARIO_7PASOS = new HashSet<CALENDARIO_7PASOS>();
            this.CITAS = new HashSet<CITAS>();
            this.CONFERENCIAS = new HashSet<CONFERENCIAS>();
            this.CUESTIONARIO_CONOCIMIENTOS = new HashSet<CUESTIONARIO_CONOCIMIENTOS>();
            this.MEDICION_GLUCOSA = new HashSet<MEDICION_GLUCOSA>();
            this.PESO_TALLA = new HashSet<PESO_TALLA>();
            this.USUARIO = new HashSet<USUARIO>();
            this.PRUEBA_BECK = new HashSet<PRUEBA_BECK>();
            this.Recomendaciones = new HashSet<Recomendaciones>();
        }
    
        public int ID_PERSONA { get; set; }
        public Nullable<int> EDAD { get; set; }
        public string NOMBRE { get; set; }
        public int ANIOSCONDIABETES { get; set; }
        public string APELLIDO_PATER { get; set; }
        public string APELLIDO_MATER { get; set; }
        public System.DateTime FECHA_INICIO { get; set; }
        public string TELEFONO { get; set; }
        public string DIRECCION { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CALENDARIO_7PASOS> CALENDARIO_7PASOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CITAS> CITAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONFERENCIAS> CONFERENCIAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CUESTIONARIO_CONOCIMIENTOS> CUESTIONARIO_CONOCIMIENTOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MEDICION_GLUCOSA> MEDICION_GLUCOSA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PESO_TALLA> PESO_TALLA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USUARIO> USUARIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRUEBA_BECK> PRUEBA_BECK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Recomendaciones> Recomendaciones { get; set; }
    }
}
