//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diabetes_Final.DataBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class PESO_TALLA
    {
        public int ID_PESO_TALLA { get; set; }
        public System.DateTime FECHA_PESO_TALLA { get; set; }
        public double RESULTADO_PESO { get; set; }
        public double RESULTADO_TALLA { get; set; }
        public int ID_PERSONA { get; set; }
    
        public virtual PERSONAS PERSONAS { get; set; }
    }
}
