//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diabetes_Final.DataBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class PREGUNTAS_CUESTIONARIO
    {
        public int ID_CUESPREGUNTA { get; set; }
        public int ID_RESPUESTAC { get; set; }
        public int ID_PREGUNTAC { get; set; }
        public int ID_CUESTIONARIO { get; set; }
    
        public virtual CUESTIONARIO_CONOCIMIENTOS CUESTIONARIO_CONOCIMIENTOS { get; set; }
        public virtual PREGUNTA_C PREGUNTA_C { get; set; }
        public virtual RESPUESTA_C RESPUESTA_C { get; set; }
    }
}
