//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diabetes_Final.DataBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recomendaciones
    {
        public int ID_RECOMENDACION { get; set; }
        public string TXT_RECOMENDACION { get; set; }
        public int ID_PERSONA { get; set; }
    
        public virtual PERSONAS PERSONAS { get; set; }
    }
}
