//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diabetes_Final.DataBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public int ID_USUARIO { get; set; }
        public string TELEFONO { get; set; }
        public string CONTRASENA { get; set; }
        public int ID_PERSONA { get; set; }
        public int ID_TIPO_USUARIO { get; set; }
        public int ID_ESTATUS { get; set; }
    
        public virtual ESTATUS_USU ESTATUS_USU { get; set; }
        public virtual PERSONAS PERSONAS { get; set; }
        public virtual TIPO_USUARIO TIPO_USUARIO { get; set; }
    }
}
